"""Unique StudentID and minor revisions

Revision ID: 0fb6faf4c35c
Revises: 4338243995fc
Create Date: 2025-05-15 16:06:17.192827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb6faf4c35c'
down_revision = '4338243995fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Share', schema=None) as batch_op:
        batch_op.drop_column('EditPower')

    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_student_unistudentid', ['UniStudentID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_unistudentid', type_='unique')

    with op.batch_alter_table('Share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EditPower', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
