"""fix data length for 2fa secret

Revision ID: 4338243995fc
Revises: 923fb848e0ff
Create Date: 2025-05-09 19:54:31.021502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4338243995fc'
down_revision = '923fb848e0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_column('Year')
        batch_op.drop_column('Units')
        batch_op.drop_column('StudentCode')
        batch_op.drop_column('Major')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Major', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('StudentCode', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('Units', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('Year', sa.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
