"""Added UniStudentID

Revision ID: 46844ec6ac20
Revises: 8d47b98175b5
Create Date: 2025-05-09 14:31:40.654497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46844ec6ac20'
down_revision = '8d47b98175b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UniStudentID', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.drop_column('UniStudentID')

    # ### end Alembic commands ###
