"""added 2fa totpsecret

Revision ID: 8d47b98175b5
Revises: 7db3c8f4c9eb
Create Date: 2025-05-05 13:18:51.916379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d47b98175b5'
down_revision = '7db3c8f4c9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.drop_column('Otp_Code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Otp_Code', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
