"""added completed check

Revision ID: 9628b126675a
Revises: 8d47b98175b5
Create Date: 2025-05-09 14:55:56.240855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9628b126675a'
down_revision = '8d47b98175b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Assignment', schema=None) as batch_op:
        batch_op.drop_column('Completed')

    # ### end Alembic commands ###
