"""Add profile fields to Student

Revision ID: c0c22c84b56f
Revises: 8d47b98175b5
Create Date: 2025-05-09 15:05:41.368180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c22c84b56f'
down_revision = '8d47b98175b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Major', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('Units', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('StudentCode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student', schema=None) as batch_op:
        batch_op.drop_column('StudentCode')
        batch_op.drop_column('Units')
        batch_op.drop_column('Year')
        batch_op.drop_column('Major')

    # ### end Alembic commands ###
